name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip nodejs

    - name: Mamba install JupyterLab 3
      shell: bash -l {0}
      run: mamba install jupyterlab=3 ipywidgets=7.6

    - name: Install ipyigv
      shell: bash -l {0}
      run: pip install .

    - name: Check installation files
      shell: bash -l {0}
      run: |
        test -d $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-ipyigv
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-ipyigv/extension.js
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-ipyigv/index.js
        test -d $CONDA_PREFIX/share/jupyter/labextensions/jupyter-ipyigv
        test -f $CONDA_PREFIX/share/jupyter/labextensions/jupyter-ipyigv/package.json

    - name: Import check
      shell: bash -l {0}
      run: python -c 'import ipyigv'
